export {default as Hero} from './Hero';
export {default as Footer} from './Footer';
export {default as Navbar} from './Navbar';
export {default as HomeCover} from './home/HomeCover';
export {default as Button} from './elements/Button';
export {default as HomeSectionI} from './home/HomeSectionI';
export {default as HomeSectionII} from './home/HomeSectionII';
export {default as HomeSectionIII } from './home/HomeSectionIII';
export {default as HomeSectionFour } from './home/HomeSectionFour';
export {default as HomeSectionFive} from './home/HomeSectionFive';
export {default as CardPoste} from './elements/CardPoste';
export {default as CardPostes} from './elements/CardPostes';
export {default as AboutCover} from './about/AboutCover';
export {default as Presentation} from './about/Presentation';
export {default as AboutSectionII } from './about/AboutSectionII';
export {default as Comment } from './about/Comment';
export {default as Principes} from './about/Principes';
export {default as DonCover} from './don/DonCover';
export {default as DonSectionI} from './don/DonSectionI';
export {default as CardDon} from './elements/CardDon';
export {default as Motivation} from './don/Motivatiion';
export {default as Contact} from './don/Contact';
export {default as ProcessCover} from './process/ProcessCover';
export {default as Souscription} from './process/Souscription';
export {default as Steps} from './process/Steps';
export {default as ProgrammeI} from './programme/ProgrammeI';
export {default as ProgrammeII} from './programme/ProgrammeII';
export {default as ProgrammeIII} from './programme/ProgrammeIII';
export {default as ProgrammeIV} from './programme/ProgrammeIV';
export {default as ProgrammeCover} from './programme/ProgrammeCover';